### PR TITLE
Axe Fix

### PR DESCRIPTION
**Pull request by eon704**
## Changes:
- Added new trap method `OnDetonateTrapAnimationComplete` which can be triggered by animation event.
- Slightly updated axe animations

## Recording:

Axe

### CODE REVIEW

**Review by Eryngii01 — COMMENTED** [review]
When I run the game, The axe is detonated but never destroyed so the hero constantly gets hurt by it...I can't seem to find where OnDetonateTrapAnimationCompete() is being called

**Review by Eryngii01 — CHANGES_REQUESTED** [review]
Accidentally commented instead of requesting changes, sorry ^^

**Comment by eon704** [comment]
Hmm, that's weird, it works on my end when I load the project. 
`OnDetonateTrapAnimationCompete()` is called by the animation event at the end of the `detonate_axe` animation.

Do you have more details on how to reproduce the issue? 😅

**Review by Eryngii01 — APPROVED** [review]
It works perfectly now! Thank you!

**Pull request merged**
