### PR TITLE
Pause UI Updates

### PR DESCRIPTION
**Pull request by eon704**
## Changes:
- Added a button to Pause game in the Game Scene.
- Added `Mute Music` and `Mute SFX` settings to the `PauseUI`. Toggling them on enables/disables corresponding audio.

## Screenshots:

Pause Button:
PauseButton

New Settings:
NewSettings

### CODE REVIEW

**Review by Eryngii01 — APPROVED** [review]
Looks good to me! 😄 

The SFX from the dialogue still plays when the mute SFX setting is toggled, but if this was done on purpose to separate the narrative SFX from the in-game SFX that works too!

**Comment by eon704** [comment]
Totally missed that! 
Good catch, thank you, will get on it 👌

**Comment by eon704** [comment]
Wasn't sure if the `Ak.Wwise.Event` of `Hero`, `HeroMovement`, and `YarnCharacterView` should be kept in respective files or if they should be moved to `AudioManager` 😅
So I'm leaving them where they are for now, if they need to be moved let's do that in a separate PR 👌

**Comment by Eryngii01** [comment]
Yeah, I saw that too and planned to change it in a future PR since it kind of scatters all that logic and makes it harder to find in the codebase 😅

**Comment by Eryngii01** [comment]
Looks good to me! 👍

**Review by Eryngii01 — APPROVED** [review]
Looks good to me! The changes work well! 👍

**Pull request merged**
