### PR TITLE
Icicle trap 2

### PR DESCRIPTION
**Pull request by Kevin22888**
Implement Icicle Trap: We are using a RigidBody 2D on this icicle trap. It starts falling when the hero walks into a trigger Box Collider, then it damages the hero if the second Box Collider (close to its sprite) collides with the hero.

(Note that if it does not hit a hero when falling down, it will stay on the platform until a hero collides with it)

Changes:
- Imported icicle trap sprites in `Assets/Art/Animations/Traps/`
- Created icicle trap prefab
- Icicle trap script in `Code/Scripts/Traps/`
- Miscellaneous changes in Game scene: new trap bar icon (just a placeholder for now), new item in trap selection bar.

Additional notes:
- need a icicle trap icon
- may need to adjust trap status (e.g. damage, build duration)

### CODE REVIEW

**Review by eon704 — CHANGES_REQUESTED** [review]
Nice work! Overall everything looks good!

Just a few nitpicks from me:
- There are some unused `using` statements in the `IcicleTrap.cs` which need to be cleaned up.
- A print statement there as well, would be nice to keep the console clean. Better to remove it before the merge 🙏 
- When building the trap, it seems to be offset from the grid by 0.5 away from the player. Feels off, should be addressed before merge 😅

Offset

- Nice-to-have: would it be possible to adjust the building projection (green building location preview tiles) to be on the ceiling by chance? Perhaps something similar to how the acid trap's preview appears in the ground.

Acid Pit

**Comment by eon704** [comment]
Also a quick comment, for the screenshots:
- The icicle trap in the trap bar appears different from your branch because I changed the colour of the icon a tiny bit (I was checking that the selection animation plays and shows the selected highlight) 👌

**Comment by Kevin22888** [comment]
Made the changes!

As for the green trap building preview, I think the ceiling is not treated the same way as the floor, so we have to use a validation score of 0 in order to place it on the top. But another problem is that the walk sound effect will always be playing when the preview box is not touching the floor. I haven't looked into how Wwise works so I'm not sure what's causing the audio problem.

**Review by eon704 — APPROVED** [review]
LGTM!

**Pull request merged**
