### PR TITLE
Data analytics

### PR DESCRIPTION
**Pull request by Eryngii01**
- Organized and documented the PlayerController class
- Separated the Trap placement logic from the PlayerController class into a TrapController class for better organization and readability
- Adapted the PlayerController class to use the Command pattern as an attempt to record input...Although this didn't work, kept the command logic for future expansion in case we want to provide undo and redo functionality for trap building that can be implemented easily with this
- Adjusted the PlayerController to record input events and generate a file with such events both in the editor and in builds to collect more playtest data (Didn't test with iOS or Android, but should work)
- Implemented a RecordingController to parse any of the generated input files to recreate the playtest sessions

**Note**:
- There is a small margin of error in the replaying of playtest sessions, so it would be best to replay a session a few times just in case...

**How to Use**:
1. In a build or editor, play the game until the end (hero dies or hen fails) to automatically generate a script
2. Navigate to Assets>InputRecordings (in Editor) or Henchman_Data>InputRecordings (in Build) to locate the generated file of the sessions.
3. Make sure to copy/move the generated file to Assets>InputRecordings for replaying the session and go to the "Playtest Analytics Gym" scene
4. Go to the Player object in the hierarchy and copy the name of the file into the field for "File Path" under the RecordingController script

### CODE REVIEW

**Review by eon704 — CHANGES_REQUESTED** [review]
Code looks overall good!
Getting Unity error of missing `AudioManager.cs` though, also some UI issues in the game scene similar to the ones we previously had - perhaps merging main into this branch should fix most of those things 😅

**Comment by Eryngii01** [comment]
Aww not again! 😅
Thanks for the catch! I'll merge main in first, and troubleshoot the weird AudioManager bug by the end of tomorrow!

**Comment by Eryngii01** [comment]
The AudioManager and UI problem should be fixed!

The playtest record player should be updated now to include the stuck logic (without firing extra Analytics events) and with the new changes to the game scene!

**Review by eon704 — APPROVED** [review]
LGTM!
Love the new Drag & Drop feature for the Heatmap!

**Pull request merged**
