### PR TITLE
Code Assembly Definitions and Documentation

### PR DESCRIPTION
**Pull request by Eryngii01**
Refactored the codebase with the following changes:
- Created a root namespace for both the Unity Editor and the project solution
- Generated assembly definitions for Editor scripts, and runtime scripts including Cameras, Common, Core, Dialogue, Environment, Heatmaps, Heroes, Input, Managers, Model, Tiles, Traps, UGSAnalytics, and UI to cut down compilation times (<15s on average) and establish hard boundaries between modules.
NOTE: At the expense of having the Core namespace (GameManager and Player related classes) dependent on every other namespace under the sun, the other assembly dependencies are all limited to **a maximum of 4 assembly definition dependencies** (with the exception of the UI assembly definition). Most assemblies only have a reference to 1 or 2 other assemblies.
Architecture
- Removed dependencies on the Core.Player namespace from the Hero, Traps, and UI namespaces by instead interfacing IDamageable and ITrapBuilder types from the Common namespace. Doing this also opens the codebase to easier future expansions on objects that can be damageable (e.g. environment objects, platforms, summoned monsters, etc.) and build traps (e.g. helper monsters summoned to build unfinished traps?)
- Made the audio implementation for the Hero and Dialogue namespaces consistent with the Core.Player namespace to each include their own SoundsControllers that indirectly communicate with the AudioManager that holds all references to the Ak.Wwise.Events, thus eliminating assembly dependencies on the Ak.WwiseTypes assembly outside of the Managers assembly. Each SoundController lies in the respective namespace (i.e. HeroSoundsController in Heroes, DialogueSoundsController in Dialogue...)
- Discovered an unused HeroDeath SFX and integrated this into the game
- Added Tooltips to class fields to provide a description in the editor inspector
- Added XML documentation for every class to leave a breadcrumb trail of what events are invoked by what methods, what methods listen on what events, etc. with links to jump to referenced source code easily. This isn't perfect though and I probably missed a lot of references, so feel free to point them out and I'll update them! 😄 
- Organized some lengthy scripts with headers and collapsible regions and attempted to make indentations, access modifiers (added internal to some), code style, etc. consistent (Also feel free to point these out too!)

NOTE: An example playthrough sequence with this architecture would be GameManager & Player inits all level, UI data -> when the level plays, GameManager & Player instantiates Heroes and Traps -> Heroes, Player, and Traps interact with each other via interfaces + UnityEvents

### CODE REVIEW

**Review by eon704 — APPROVED** [review]
LGTM, PR is good to go!

A little comment on my end: I am not sure if we should use the `KrillOrBeKrilled`. Kind of feels that it's Will's thing and not ours, and half of the team are different people. Perhaps we need to switch to something else later on. 😅 

Not urgent tho! Just some thoughts I wanted to share. **PR is good to go**, thank you for all the hard work of documenting so much of the code! 🔥

**Comment by eon704** [comment]
Another comment: standardizing our code style may be a good idea. Things like:
- Indentation
- Naming
- Brackets style and line position
- Documenting new methods / variables

Then in each new PR we will know that all of the new code is properly documented and the whole codebase remains up-to-date.

Should be easier to document new code on the go 😅 👌 
What do you think? 😄

**Comment by Eryngii01** [comment]
Yeah, I wasn't too sure about the ```KrillOrBeKrilled``` namespace too for that same reason but unfortunately couldn't think of any better name so I just put the organization name, but this would be a really easy change to make in the future! I'll add this to the design meeting discussion document! 👌 

On the note of code style standardization, I think that's a great idea! After looking through the codebase with the documentation overall, I did notice that there are very slight differences between our styles so I did make some changes already, but I think it would be best to discuss this with everyone before making the final merge so I can correct things and that everyone will be on the same page! 😄 

I could make a little copy-and-paste documentation template and add it to the Trello and/or Discord if that would help for future updates to the code 👌 
On that note, I should also add a guide for the assemblies and code architecture too (probably on the Trello)

**Comment by eon704** [comment]
Sounds good! 😄 
A note on Trello sounds like a good idea 👌

**Pull request merged**
